on:
  pull_request_target:
    types: [closed]
  workflow_dispatch:
    inputs:
      user:
        description: "GitHub username"
        required: true
        type: string
      outstanding:
        description: "Was the contribution outstanding?"
        required: false
        type: boolean

permissions:
  issues: write
  pull-requests: write

jobs:
  issue_lava_lamp_holobyte:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: contribution
